[package]
name = "discord-delete-echo"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies.discord]
git = "https://github.com/SpaceManiac/discord-rs.git"
# disable "voice" -> opus/sodiumoxide
default-features = false
features = []
